MagicPlaceFront/Controllers/OccupantController.cs
using AutoMapper;
using MagicPlace_Utilities;
using MagicPlaceFront.Models;
using MagicPlaceFront.Models.Dto;
using MagicPlaceFront.Models.ViewModel;
using MagicPlaceFront.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;
using Newtonsoft.Json;
using System.Data;
using System.Reflection;

namespace MagicPlaceFront.Controllers
{
    public class OccupantController : Controller
    {

        private readonly IOccupantServices _services;
        private readonly IRoomServices _roomServices;
        private readonly IMapper _mapper;

        public OccupantController(IOccupantServices services, IRoomServices roomServices, IMapper mapper)
        {
            _services = services;
            _roomServices = roomServices;
            _mapper = mapper;
        }





        [Authorize(Roles = "admin")]
        public async Task<IActionResult> IndexOccupants()
        {

            List<OccupantDto> listOccupants = new();

            var response = await _services.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                listOccupants = JsonConvert.DeserializeObject<List<OccupantDto>>(Convert.ToString(response.Results));

            }

            return View(listOccupants);
        }



        //Creacion de nuevo ocupante 
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddOccupant()
        {

            OcuppantViewModel vmOccupant = new();

            //obtenemos las habitaciones 

            var response = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                vmOccupant.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(response.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }
            return View(vmOccupant);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOccupant(OcuppantViewModel modelo)
        {

            if (ModelState.IsValid)
            {

                var response = await _services.Create<ApiResponse>(modelo.ObjOccupant , HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.isSucces)
                {
                    TempData["isSucces"] = "Inquilino Agregado Exitosamente";
                    return RedirectToAction(nameof(IndexOccupants));

                }
                else
                {
                    TempData["error"] = "Error al agregar inquilino";
                    if (response.ErrorMessages.Count > 0)
                    {

                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());

                    }

                }

            }

            
            //TODO : enviar la lista de sleccion de Habitacion nuevamente

            var res = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (res != null && res.isSucces)
            {

                modelo.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(res.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }

            return View(modelo);

        }



        //update Occupant 

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateOccupant(int IdCard)
        {

            OcuppantUpdateViewModel vmUpdateOccupant = new();

            var response = await _services.GetById<ApiResponse>(IdCard , HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                OccupantDto modelo = JsonConvert.DeserializeObject<OccupantDto>(Convert.ToString(response.Results));
                vmUpdateOccupant.ObjOccupant = _mapper.Map<OccupantUpdateDto>(modelo);
            }

            //obtenemos las habitaciones 

            response = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                vmUpdateOccupant.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(response.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }
            return View(vmUpdateOccupant);

        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateOccupant(OcuppantUpdateViewModel modelo)
        {


            if (ModelState.IsValid)
            {

                var response = await _services.Update<ApiResponse>(modelo.ObjOccupant , HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.isSucces)
                {
                    TempData["isSucces"] = "Inquilino actualizado";

                    return RedirectToAction(nameof(IndexOccupants));

                }
                else
                {

                    if (response.ErrorMessages.Count > 0)
                    {

                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());

                    }

                }


            }


            //TODO : enviar la lista de sleccion de Habitacion nuevamente

            var res = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (res != null && res.isSucces)
            {

                modelo.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(res.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }

            TempData["error"] = "Algo salio mal";


            return View(modelo);
        }


        //delete Occupant 
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteOccupant(int IdCard)
        {

            OcuppanDeleteViewModel vmDeleteOccupant = new();

            var response = await _services.GetById<ApiResponse>(IdCard , HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                OccupantDto modelo = JsonConvert.DeserializeObject<OccupantDto>(Convert.ToString(response.Results));
                vmDeleteOccupant.ObjOccupant = modelo;
            }

            //obtenemos las habitaciones 

            response = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                vmDeleteOccupant.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(response.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }
            return View(vmDeleteOccupant);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOccupant(OcuppanDeleteViewModel modelo)
        {


            if (modelo.ObjOccupant.IdCard > 0)
            {

                var response = await _services.DeleteById<ApiResponse>(modelo.ObjOccupant.IdCard, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.isSucces)
                {
                    TempData["isSucces"] = "Inquilino Eliminado Exitosamente";
                    return RedirectToAction(nameof(IndexOccupants));

                }
                else
                {

                    if (response.ErrorMessages.Count > 0)
                    {

                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());

                    }

                }

            }







            //TODO : enviar la lista de sleccion de Habitacion nuevamente

            var res = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (res != null && res.isSucces)
            {

                modelo.RoomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(res.Results)).
                                      Select(r => new SelectListItem
                                      {

                                          Text = r.Name,
                                          Value = r.Id.ToString()

                                      });

            }

            return View(modelo);
        }
    }
}

MagicPlaceFront/Controllers/RoomController.cs
using AutoMapper;
using MagicPlace_Utilities;
using MagicPlaceFront.Models;
using MagicPlaceFront.Models.Dto;
using MagicPlaceFront.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Packaging.Signing;

namespace MagicPlaceFront.Controllers
{
    public class RoomController : Controller
    {

        private readonly IRoomServices _roomServices;
        private readonly IMapper _mapper;

        public RoomController(IRoomServices roomServices, IMapper mapper)
        {

            _roomServices = roomServices;
            _mapper = mapper;


        }

        [Authorize(Roles ="admin")]
        public async Task<IActionResult> IndexRoom()
        {

            List<RoomDto> roomList = new();
            var response = await _roomServices.GetAll<ApiResponse>(HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                roomList = JsonConvert.DeserializeObject<List<RoomDto>>(Convert.ToString(response.Results));

                //le pasamos la lista a la vista 
                return View(roomList);
            }
            return NotFound();
            
        }



        //Crear nueva Habitacion
        //Get------> ya que a los metodos cuando no se les define un tipo por defecto son GET

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateRoom()
        {
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRoom(RoomCreateDto dto)
        {

            if (ModelState.IsValid)
            {

                var response = await _roomServices.Create<ApiResponse>(dto, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.isSucces)
                {
                    TempData["isSucces"] = "Habitacion Creada Exitosamente";
                    return RedirectToAction(nameof(IndexRoom));
                }
            }
            TempData["error"] = "Falla en la carga de datos";


            return View(dto);

        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateRoom(int id)
        {
            var response = await _roomServices.GetById<ApiResponse>(id, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                RoomDto model = JsonConvert.DeserializeObject<RoomDto>(Convert.ToString(response.Results));

                return View(_mapper.Map<RoomUpdateDto>(model));

            }

            return NotFound();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRoom(RoomUpdateDto roomToUpdate) {

            if (ModelState.IsValid) { 

                var response = await _roomServices.Update<ApiResponse>(roomToUpdate, HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.isSucces) {

                    TempData["isSucces"] = "Habitacion Actualizada";
                    return RedirectToAction(nameof(IndexRoom));

                }
                TempData["error"] = "Algo fallo en la actualizacion";

            }

            return View(roomToUpdate);

        }


        //delete Room
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteRoom(int id)
        {
            var response = await _roomServices.GetById<ApiResponse>(id, HttpContext.Session.GetString(SD.SessionToken));

            if (response != null && response.isSucces)
            {

                RoomDto model = JsonConvert.DeserializeObject<RoomDto>(Convert.ToString(response.Results));

                return View(model);

            }

            return NotFound();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRoom(RoomDto roomDto)
        {

            if (ModelState.IsValid)
            {

                var response = await _roomServices.DeleteById<ApiResponse>(roomDto.Id , HttpContext.Session.GetString(SD.SessionToken));

                if (response != null && response.isSucces)
                {

                    return RedirectToAction(nameof(IndexRoom));

                }
            }

            return View(roomDto);

        }

    }
}

MagicPlaceFront/Controllers/UserController.cs
using MagicPlace_Utilities;
using MagicPlaceFront.Models;
using MagicPlaceFront.Models.Dto;
using MagicPlaceFront.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MagicPlaceFront.Controllers
{
    public class UserController : Controller
    {

        public readonly IUserService _userService;

        public UserController(IUserService userService)
        {

            _userService = userService;
        }


        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto dto)
        {
            var response = await _userService.Login<ApiResponse>(dto);

            if (response != null && response.isSucces == true)
            {

                LoginResponseDto responseDto = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Results));


                //aqui mediante la libreria Extraeremos el token del responseDto

                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(responseDto.Token);


                //configuracion de los Claims esto es para mantener el user name y el role en todo Momento 

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(tok => tok.Type == "name").Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(tok => tok.Type == "role").Value));
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                //configuracion de la sesion 
                HttpContext.Session.SetString(SD.SessionToken, responseDto.Token);

                //vamosa retoenar a una vista de index pero como en este  caso la vista no se encuentra en el mismo 
                //constrolador lo que haremos sera indicarle como segundo parametro dl metodo el nombre del controlador 

                return RedirectToAction("Index", "Home");
            }
            else
            {

                ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                return View(dto);

            }

         
        }


        //register

        public IActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterRequestDto dto)
        {

            var response = await _userService.Register<ApiResponse>(dto);
            if (response != null && response.isSucces)
            {

                return RedirectToAction("login");

            }
            return View();
        }



        //metodo cierre de sesion 


        public async Task<IActionResult>Logout()
        {

            //clean Session Variable 
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken,"");
            return RedirectToAction("Index","Home");

        }

        //acces denied

        public IActionResult AccessDenied()
        {
            return View();

        }





    }
}

MagicPlaceFront/Views/Shared/_Layout.cshtml
@using MagicPlace_Utilities;
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAcc;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicPlaceFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicPlaceFront.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_NotifiedSciptPartial" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MagicPlaceFront</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="IndexRoom">Room's'</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Occupant" asp-action="IndexOccupants">Occupant's</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex">
                        @if (httpContextAcc.HttpContext.Session.GetString(SD.SessionToken) != null &&
                        httpContextAcc.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Registrar</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MagicPlaceFront - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicPlaceFront/Views/Shared/_NotifiedSciptPartial.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@*y aqui Haremos uso de Temp Data  los cuales son datos que uno utiliza y se borran en el momento n el que
se desplegan*@



@if (TempData["isSucces"] != null)
{
    <script>

        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["isSucces"]',
            showConfirmButton: false,
            timer: 1500
        })

    </script>



}

@if (TempData["error"] != null)
{
    <script>

        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 1500
        })

    </script>



}